name: 'Build PDF version'
on:
  workflow_dispatch:
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Create PDF
        run:
          docker run --rm -i -v $(pwd)/pdf:/app/pdf
          openbayes/docusaurus-prince-pdf --output pdf/docs.pdf -u
          https://docs.dorpflege.rössing.de
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          # The output filename can be specified with --output option
          path: pdf/docs.pdf
          if-no-files-found: error
