name: 'Build PDF version'
on:
  workflow_dispatch:
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Install Prince
        run: |
          curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
          tar zxf prince-14.2-linux-generic-x86_64.tar.gz
          cd prince-14.2-linux-generic-x86_64
          yes "" | sudo ./install.sh
      - name: Create PDF
        run:
          npx docusaurus-prince-pdf --output pdf/docs.pdf -u
          https://docs.dorfpflege.xn--rssing-wxa.de/
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          # The output filename can be specified with --output option
          path: pdf/docs.pdf
          if-no-files-found: error
